a=input('Enter the First Number :')
b=input('Enter the Second Number :')
c= int(a)+int(b)
print("Additon: ",c)
c= int(a)-int(b)
print("Subtraction:  ",c)
c= int(a)*int(b)
print("Multiplication: ",c)
c= int(a)/int(b)
print("Division: ",c)